import {createClient} from './http.mjs';
import {normalizeJobLocations,jobCityStatus} from './locations.mjs';
const text=v=>String(v??'').replace(/<(?:br\s*\/?|\/p|\/div|\/li)>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim();
const base=(source,j,file)=>{const loc=normalizeJobLocations(j);return{company_id:source.company_id,company_name:source.display_name,...j,cities:loc.cities,location_special:loc.special,location_unknown:loc.unknown,location_unresolved:loc.unresolved,body_complete:!!(j.description?.trim()&&j.requirements?.trim()),raw_file:file,evidence_files:[file],jd_origin:'public_api',checked_at:new Date().toISOString()};};
async function mapLimit(items,n,fn){let cursor=0;await Promise.all(Array.from({length:n},async()=>{while(cursor<items.length)await fn(items[cursor++]);}));}
const ok=r=>{if(r.record.http_status!==200||!r.data)throw Error('Public API HTTP '+r.record.http_status);if(r.data.code!==undefined&&Number(r.data.code)!==0)throw Error('API code '+r.data.code+': '+(r.data.msg||r.data.message));return r.data;};
export async function collectOemPublic(source,options={}){
 if(source.provider==='aion_public')return collectAionPublic(source,options);
 if(!['byd_public','lixiang_public','sinotruk_public'].includes(source.provider))return null;
 const o={maxPages:1000,pageSize:50,mode:'full',timeoutMs:30000,...options},client=createClient(o),jobs=new Map(),pages=[],errors=[];let total=null,listComplete=false;
 const send=client.request.bind(client);client.request=async(...args)=>{try{return await send(...args);}catch(e){if(!/timeout|fetch failed|aborted/i.test(e.message))throw e;return await send(...args);}};
 try{
 if(source.provider==='lixiang_public'){
   const origin='https://www.lixiang.com',list='/osd-hr-recruitment-website/v1/recruit/school/job-page',rows=new Map();
   for(let page=1;page<=o.maxPages;page++){
    const r=await client.request({url:origin+list+'?page='+page+'&page_size='+o.pageSize+'&job_mode=1'},{purpose:'formal_campus_job_list'}),d=ok(r).data;if(!Array.isArray(d?.items))throw Error('Missing items');total=d.total_count;let added=0;for(const row of d.items){if(!rows.has(String(row.id))){rows.set(String(row.id),{row,file:r.record.response_file});added++;}}
    pages.push({page,request_index:r.record.index,response_file:r.record.response_file,job_ids:d.items.map(j=>String(j.id)),server_total:total});if(rows.size===Number(total)){listComplete=true;break;}if(!added){errors.push('No new IDs before server total');break;}
   }
   await mapLimit([...rows.values()],3,async({row,file})=>{try{const r=await client.request({url:origin+'/osd-hr-recruitment-website/v1/recruit/job/detail?job_id='+encodeURIComponent(row.id)},{purpose:'job_detail'}),d=ok(r).data;if(String(d?.id)!==String(row.id))throw Error('Detail ID mismatch');const j=base(source,{job_id:String(d.id),title:d.title,description:text(d.description),requirements:text(d.requirements),locations_raw:[d.location_title].filter(Boolean),formal_status:d.job_mode==='201'&&/校园|校招/.test(d.subject_name||'')?'formal':/实习/.test(d.job_mode_name||'')?'internship':'unknown',open_status:'open',official_url:origin+'/employ/detail/'+d.id+'.html?jobCode='+encodeURIComponent(d.code||''),job_url_kind:'official_detail',recruitment_evidence:{provider:source.provider,job_mode:d.job_mode,job_mode_name:d.job_mode_name,subject_name:d.subject_name,public_list_returned:true},raw_metadata:{department:d.department_title,job_function:d.second_job_function_title}},r.record.response_file);jobs.set(j.job_id,j);}catch(e){errors.push(String(row.id)+': '+e.message);}});
 }else if(source.provider==='byd_public'){
   const origin='https://job.byd.com',api=origin+'/portal/api/portal-api';const conf=await client.request({url:api+'/postEntryConfig/list'},{purpose:'public_recruitment_type_configuration'}),cfg=ok(conf).data;const contexts=cfg.filter(c=>c.status==='00111'&&c.postEntryName==='应届生');if(!contexts.length)throw Error('No active current graduate context');const rows=new Map();
   try { for(const context of contexts){let count=null,seen=new Set();for(let page=1;page<=o.maxPages;page++){
     const body={topicCode:'',batch:context.batch,campusNature:context.campusNature,abroad:'',degree:'',jobType:[],researchDirection:[],workPlace:[],keywords:'',pageSize:source.list_page_size||500,pageIndex:page};
     const r=await client.request({url:api+'/schoolPortal/queryPositionList',method:'POST',body},{purpose:'formal_campus_job_list'}),d=ok(r);if(!Array.isArray(d.data))throw Error('Missing positions');count=d.page?.totalCount;total=count;let added=0;for(const row of d.data){const id=String(row.id);if(!seen.has(id)){added++;seen.add(id);}rows.set(id,{row,context,file:r.record.response_file});}pages.push({page,request_index:r.record.index,response_file:r.record.response_file,job_ids:d.data.map(j=>String(j.id)),server_total:count});if(seen.size===Number(count)){listComplete=true;break;}if(!added){errors.push('No new IDs before server total');break;}
   }} } catch(e) { errors.push('list: '+e.message); }
   await mapLimit([...rows.values()],3,async({row,context})=>{try{const r=await client.request({url:api+'/schoolPortal/queryPosition?id='+encodeURIComponent(row.id)},{purpose:'job_detail'}),d=ok(r).data;if(String(d?.id)!==String(row.id))throw Error('Detail ID mismatch');if(!Array.isArray(d.positionInfoList)||!d.positionInfoList.length)throw Error('No position variants');for(const v of d.positionInfoList){const j=base(source,{job_id:String(d.id)+':'+String(v.id),title:d.jobName,description:text(v.jobDuty),requirements:text(v.jobRequirements),locations_raw:[v.workPlace||d.workPlace].filter(Boolean),formal_status:d.campusNature===context.campusNature?'formal':'unknown',open_status:'open',official_url:origin+'/portal/pc/#/school/schoolPositionDetail?id='+d.id,job_url_kind:'official_detail',recruitment_evidence:{provider:source.provider,post_entry_name:context.postEntryName,batch:context.batch,campusNature:d.campusNature,current_entry_status:context.status,cohort_requirement:context.content,public_list_returned:true},raw_metadata:{parent_job_id:d.id,position_variant_id:v.id,division:v.division,research_direction:v.researchDirection,degree_code:v.degree}},r.record.response_file);jobs.set(j.job_id,j);}}catch(e){errors.push(String(row.id)+': '+e.message);}});
 }else{
   const origin='https://zhaopin.sinotruk.com:8009',api=origin+'/hrapi/hr.recruit/data/hrMrRecruitmentNoticePositions';
   for(let page=1;page<=o.maxPages;page++){const r=await client.request({url:api+'/selectMrPosition',method:'POST',body:{currentPage:page,pageSize:o.pageSize}},{purpose:'campus_job_list'}),d=ok(r);if(!Array.isArray(d.records))throw Error('Missing records');total=d.totalCount;let added=0;for(const v of d.records){const id=String(v.noticePositionId||v.id);if(jobs.has(id))continue;added++;const desc=text(v.duty),req=[v.demandMajor?`需求专业：${text(v.demandMajor)}`:'',v.demandEducatioin?`学历代码（待核实名称）：${v.demandEducatioin}`:''].filter(Boolean).join('\n');const j=base(source,{job_id:id,title:v.positionName,description:desc,requirements:req,locations_raw:[v.workZoneStr].filter(Boolean),formal_status:/校招|校园招聘/.test(v.title||v.newsTitle||'')?'formal':'unknown',open_status:'unknown',official_url:origin+'/#/schoolRecruit/item/'+id,job_url_kind:'official_detail',recruitment_evidence:{provider:source.provider,title:v.title,news_title:v.newsTitle,batch_code:v.batchCode,published_list_returned:true,open_status_note:'Public list exposes older campus cohorts without closing status; do not assume currently accepting applications.'},raw_metadata:{work_zone_code:v.workZone,education_code:v.demandEducatioin,notice_id:v.noticeId,org_name:v.orgName}},r.record.response_file);jobs.set(id,j);}pages.push({page,request_index:r.record.index,response_file:r.record.response_file,job_ids:d.records.map(j=>String(j.id)),server_total:total});if(jobs.size===Number(total)){listComplete=true;break;}if(!added){errors.push('Repeated page');break;}}
 }
 }catch(e){errors.push(e.message);}
 const missing=[...jobs.values()].filter(j=>!j.body_complete).length;if(missing)errors.push(missing+' jobs lack either duties or requirements');
 return {company_id:source.company_id,display_name:source.display_name,checked_at:new Date().toISOString(),jobs:[...jobs.values()],requests:client.records,coverage:{status:listComplete&&!errors.length?'complete':jobs.size?'partial':'failed',list_complete:listComplete,pages:pages.length,server_total:total,jobs_observed:jobs.size,reason:errors.length?errors.join('; '):listComplete?'unique listing IDs reconcile server total':'max_pages_reached',page_evidence:pages,details_failed:errors.length,note:source.provider==='byd_public'?'Server total counts grouped job titles; output separates each positionInfoList variant by parent:variant ID.':undefined}};
}
export async function collectAionPublic(source,options={}){
 const c=createClient(options),jobs=new Map(),pages=[],errors=[],headers={'Content-Type':'application/x-www-form-urlencoded',channel:'H5'};let complete=true;
 for(const type of [2,1]){let pageCount=1;for(let page=1;page<=Math.min(pageCount,options.maxPages||1000);page++){try{const r=await c.request({url:'https://www.aion.com.cn/Home/Api/getJoin',method:'POST',headers,body:new URLSearchParams({page:String(page),type:String(type)})},{purpose:type===2?'campus_job_list':'social_capability_job_list'});if(r.record.http_status!==200||Number(r.data?.code)!==200)throw Error('Aion public API failed');const d=r.data.data;if(!Array.isArray(d?.data))throw Error('Missing Aion list');pageCount=Number(d.num)||0;pages.push({page,type,total_pages:pageCount,job_ids:d.data.map(j=>String(j.id)),response_file:r.record.response_file});for(const row of d.data){const detail=await c.request({url:'https://www.aion.com.cn/home/api/getJoindetail',method:'POST',headers,body:new URLSearchParams({id:String(row.id)})},{purpose:'job_detail'});if(detail.record.http_status!==200||Number(detail.data?.code)!==200||String(detail.data?.data?.id)!==String(row.id))throw Error('Aion detail identity invalid');const x=detail.data.data;const j=base(source,{job_id:String(x.id),title:x.jobs||x.job_title,description:text(x.responsibility),requirements:text(x.post_requirements),locations_raw:[x.ads].filter(Boolean),formal_status:/社会/.test(x.type)?'social':/校园/.test(x.type)?'formal':'unknown',open_status:'unknown',official_url:'https://www.aion.com.cn/show/joindetail?id='+x.id+'&type='+type,job_url_kind:'official_detail',recruitment_evidence:{provider:'aion_public',type:x.type,publish_date:x.addtime,open_status_note:'Official API still exposes 2018 postings without explicit current availability; source retained only as API capability.'}},detail.record.response_file);jobs.set(j.job_id,j);}}catch(e){complete=false;errors.push(e.message);break;}}if(pageCount>(options.maxPages||1000))complete=false;}
 return {company_id:source.company_id,display_name:source.display_name,checked_at:new Date().toISOString(),jobs:[...jobs.values()],requests:c.records,coverage:{status:complete?'complete':jobs.size?'partial':'failed',list_complete:complete,pages:pages.length,server_total:null,jobs_observed:jobs.size,reason:errors.join('; ')||'API page counts exhausted; old job dates and unknown open status retained',page_evidence:pages}};
}
