import{createClient}from'./http.mjs';import{normalizeJobLocations}from'./locations.mjs';
const plain=s=>String(s||'').replace(/<\/(?:p|div)>|<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim(),placeholder=s=>/请您详见岗位意向|请选择.*岗位意向/.test(s);
export async function collectHuawei(source,options={}){
 const client=createClient(options),base='https://apigw-dgg-b0.huawei.com/api/apig/channelhw',headers={'X-HW-ID':'app_000000035886','x-jalor-tenantAlias':'hcm','x-language':'zh_CN','x-Referer':'https://career.huawei.com/cn',Origin:'https://career.huawei.com',Referer:'https://career.huawei.com/'},ads=new Map(),jobs=[],pages=[],failures=[];let total=null,listComplete=false;
 for(let p=1;p<=(options.maxPages||100);p++){const r=await client.request({url:base+'/recruitmentPosition/pub/getJobPage?X-HW-ID=app_000000035886',method:'POST',headers,body:{curPage:p,pageSize:100,jobType:'CR',language:'zh_CN'}},{purpose:'campus_job_list'});if(r.record.http_status!==200||r.data?.status!=='SUCCESS'||!Array.isArray(r.data?.data?.result))throw Error('Huawei public list unavailable');total=Number(r.data.data.pageVO?.totalRows);let added=0;for(const d of r.data.data.result){if(!ads.has(String(d.advertisementId))){ads.set(String(d.advertisementId),{d,file:r.record.response_file});added++;}}pages.push({page:p,rows:r.data.data.result.length,response_file:r.record.response_file});if(ads.size===total){listComplete=true;break;}if(!added)break;}
 let cursor=0;const entries=[...ads.values()];async function worker(){while(cursor<entries.length){const{d,file}=entries[cursor++];let intentRows=[],intentFile=null;try{const r=await client.request({url:base+'/recruitmentPosition/pub/getPositionIntentionList?X-HW-ID=app_000000035886',method:'POST',headers,body:{jobId:d.jobId}},{purpose:'public_full_jd_intentions'});if(r.record.http_status!==200||r.data?.status!=='SUCCESS'||!Array.isArray(r.data.data))throw Error('Invalid intention API response');intentRows=r.data.data;intentFile=r.record.response_file;}catch(e){failures.push({advertisement_id:d.advertisementId,error:e.message});}
  for(const x of intentRows.length?intentRows:[null]){const description=plain(x?.jobResponsibilities||d.mainBusiness),requirements=plain(x?.jobDemand||d.jobRequire),j={company_id:source.company_id,display_name:source.display_name,job_id:String(d.advertisementId)+(x?':'+x.positionIntentionId:''),title:d.jobName+(x?' · '+x.positionIntention:''),official_url:'https://career.huawei.com/cn/job-details?advertisementId='+d.advertisementId+(x?'&positionIntentionId='+x.positionIntentionId:''),description,requirements,body_complete:description.length>15&&requirements.length>15&&!placeholder(description)&&!placeholder(requirements),locations_raw:String(x?.jobPlaceName||d.workPlace||'').split('/').filter(Boolean),formal_status:/实习/.test(d.scenarioName||'')?'internship':/应届/.test(d.scenarioName||'')?'formal':'unknown',open_status:'open',recruitment_evidence:{provider:'huawei',scenario_name:d.scenarioName,scenario_code:d.scenarioCode,advertisement_id:d.advertisementId,job_id:d.jobId,position_intention_id:x?.positionIntentionId,external_post_code:x?.externalPostCode},raw_metadata:{department:x?.deptName||d.deptName,category:d.categoryName,department_locations:x?.deptAndPlaceList,last_update_date:d.lastUpdateDate},evidence_files:[file,...intentFile?[intentFile]:[]]};const loc=normalizeJobLocations(j);jobs.push({...j,cities:loc.cities,location_unknown:loc.unknown,location_unresolved:loc.unresolved,location_special:loc.special});}
 }}await Promise.all(Array.from({length:3},worker));
 return{company_id:source.company_id,display_name:source.display_name,checked_at:new Date().toISOString(),jobs,requests:client.records,coverage:{status:listComplete&&!failures.length?'complete':'partial',list_complete:listComplete,pages:pages.length,page_evidence:pages,server_total:total,advertisements_observed:ads.size,jobs_observed:jobs.length,intention_failures:failures,reason:'Public campus advertisements paged to total; every advertised job expanded through public position-intention API; placeholder summary text is never treated as full JD'}};
}
